version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports: ["5432:5432"]
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./db/seed_candidates.sql:/docker-entrypoint-initdb.d/02_seed.sql

  collector:
    build: ./collector
    env_file: .env
    depends_on: [db]

  analyzer:
    build: ./analyzer
    env_file: .env
    ports: ["8000:8000"]
    depends_on: [db]

  dashboard:
    build: ./dashboard
    env_file: .env
    ports: ["3000:3000"]
    depends_on: [analyzer]
